name: 'ROS CI'
description: 'ROS Continuous Integration'
runs:
  using: 'composite'
  steps:
    - run: docker build --tag ros-container .
      shell: bash
    - run: docker run ros-container
      shell: bash
