name: 'ROS CI'
description: 'ROS Continuous Integration'
inputs:
  package-directory:
    description: 'Package directory'
    required: true
    default: ''
runs:
  using: 'composite'
  steps:
    - run: docker build --tag ros-container --build-arg PACKAGE_DIR=${{ inputs.package-directory }} $GITHUB_ACTION_PATH/.
      shell: bash
    - run: docker run ros-container
      shell: bash
