name: 'ROS CI'
description: 'ROS Continuous Integration'
inputs:
  package-directory:
    description: 'Package directory'
    required: true
    default: ''
runs:
  using: 'composite'
  steps:
    - run: docker build --tag ros-container --build-arg GITHUB_ACTION_PATH=$GITHUB_ACTION_PATH -f $GITHUB_ACTION_PATH/Dockerfile ${{ inputs.package-directory }}
      shell: bash
    - run: docker run ros-container
      shell: bash
